pimcore:
    workflows:
        Product_workflow:
            label: 'Product Approval'
            type: 'state_machine'
            # support_strategy:
            #     service: App\Workflow\SupportsStrategy

            marking_store:
                type: single_state
                arguments:
                    - workflowState

            supports:
                - Pimcore\Model\DataObject\Product
            initial_markings: ToReview
            places:
                ToReview:
                    # label: 'Waiting for approval'
                    label: 'In Review'
                    color: '#FFFFCC'
                    permissions:
                        -
                            condition:   is_fully_authenticated() and 'manager' in role_names
                            # condition:   is_fully_authenticated() and 'ROLE_PIMCORE_ADMIN' in role_names
                            publish: true
                            delete: true
                        -
                            condition:   is_fully_authenticated() and 'employee' in role_names
                            publish: false
                            delete: false
                            view: true
                ProductRejected:
                    label: 'Product Rejected'
                    color: '#D83A56'
                    permissions:
                        -
                            condition:   is_fully_authenticated() and 'manager' in role_names
                            publish: true
                            delete: true
                        -
                            condition:   is_fully_authenticated() and 'employee' in role_names
                            publish: false
                            delete: false
                            view: false
                ProductAccepted:
                    label: 'Product Accepted'
                    color: '#66DE93'
                    permissions:
                        -
                            condition:   is_fully_authenticated() and 'manager' in role_names
                            # condition:   is_fully_authenticated() and 'ROLE_PIMCORE_ADMIN' in role_names
                            publish: true
                            delete: true
                        -
                            condition:   is_fully_authenticated() and 'employee' in role_names
                            publish: false
                            delete: false
                            view: true
            transitions:
                approval_accepted:
                    from: ToReview
                    to: ProductAccepted
                    guard: "is_granted ('ROLE_PIMCORE_ADMIN') or is_granted ('ROLE_MANAGER')"
                    options:
                        label: 'Product Approved'
                        changePublishedState: force_published
                        notificationSettings:
                        - notifyUsers: ['admin']
                          notifyRoles: ['manager']
                          channelType:
                                - pimcore_notification
                approval_rejected:
                    from: ToReview
   #  from: toReview
                    to: ProductRejected
                    # to: product_rejected
                    guard: "is_granted ('ROLE_PIMCORE_ADMIN') or is_granted ('ROLE_MANAGER')"
                    options:
                        label: 'Product Rejected'
                        changePublishedState: force_unpublished
                        notificationSettings:
                        - notifyUsers: ['admin']
                          notifyRoles: ['manager']
                          channelType:
                                - pimcore_notification
                reset_product:
                    from: [ProductAccepted,ProductRejected]
                    to: ToReview
                    options:
                        label: 'Product Reset'
                        changePublishedState: force_unpublished